module.exports = {
  bail: 1,
  clearMocks: true,
  collectCoverage: true,
  collectCoverageFrom: ['<rootDir>/src/services/**/*.ts'],
  coverageDirectory: 'coverage',
  coverageProvider: 'v8',
  coverageReporters: ['text', 'lcov'],
  preset: 'ts-jest',
  testEnvironment: 'node',
  testMatch: ['**/__tests__/**/*.test.ts'],
  moduleNameMapper: {
    '^@configs/(.*)$': '<rootDir>/src/config/$1',
    '^@cntrls/(.*)$': '<rootDir>/src/controllers/$1',
    '^@errs/(.*)$': '<rootDir>/src/errors/$1',
    '^@help/(.*)$': '<rootDir>/src/helpers/$1',
    '^@libs/(.*)$': '<rootDir>/src/libs/$1',
    '^@middle/(.*)$': '<rootDir>/src/middlewares/$1',
    '^@p-client/(.*)$': '<rootDir>/src/prisma/$1',
    '^@routes/(.*)$': '<rootDir>/src/routes/$1',
    '^@servs/(.*)$': '<rootDir>/src/services/$1',
    '^@tp/(.*)$': '<rootDir>/src/types/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^src/(.*)$': '<rootDir>/src/$1',
    pino: '<rootDir>/node_modules/pino',
  },
  globalSetup: '<rootDir>/src/test/setup.ts',
  globalTeardown: '<rootDir>/src/test/teardown.ts',
}
